name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main   # ajusta para o branch que você quer fazer deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Rodar lint
        run: npm run lint --if-present

      - name: Build do projeto
        run: npm run build

      - name: Deploy para Firebase Hosting (mysnack-client)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "${{ secrets.FIREBASE_PROJECT_ID }}"
          target: "mysnack-backoffice"
          channelId: live
